name: HyperExplorer

permissions:
  contents: write
  issues: read
  actions: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  VERSION: "alpha-${{ github.run_number }}"

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build for Windows
      run: cargo build --release --verbose

    - name: Create Tag and Push
      run: |
        git tag ${{ env.VERSION }}
        git push origin ${{ env.VERSION }}

    - name: Upload Windows binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: hyperexplorer-windows
        path: target/release/hyperexplorer.exe

    - name: Create GitHub Release for Windows
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/hyperexplorer.exe
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build for Linux
      run: cargo build --release --verbose

    - name: Upload Linux binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: hyperexplorer-linux
        path: target/release/hyperexplorer

    - name: Create GitHub Release for Linux
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/hyperexplorer
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
